# Generated by Django 3.1.2 on 2020-11-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=32)),
                ('p_age', models.IntegerField(default=1)),
                ('p_sex', models.BooleanField(default=False)),
            ],
        ),
    ]
